PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/f79b47ad25e4f79e14ce737d8c80c1f45fbd2c56

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/fdf1837077104e80912a2c46ff159fdacc8b06f9) in current PX4/master (abd2bb4eb738eef2007c43206a353ca38d4fdf6e)
https://github.com/PX4/NuttX/compare/fdf1837077104e80912a2c46ff159fdacc8b06f9...f79b47ad25e4f79e14ce737d8c80c1f45fbd2c56

f79b47ad25 (HEAD, origin/master) tiva_serial.c: Make this buildable with certain configurations
3df686e10f sim: berr() unknown relocation type
3ead7795b2 sim: Add loadable module definitions
7f1f930a7b Remove unneeded dependency on USB
1200c6d429 Using debug macros for memory card
1832172432 Fix wrong name for CONFIG_MMCSD_SPI
0b25b96759 net/netlink/netlink_route.c:  Fix a typo.
46ad645efc mm: Add a bunch of assertions
c1a32fb9dd compiler.h: clang actually has long long
1382ea5447 mm/: Coding style clean-up

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/de4d52d465fee9cb9ed48e8d1b8d73e8f5888519

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/91b6ad6a0d00ac107088b18588cd54d40e3cb796) in current PX4/master (abd2bb4eb738eef2007c43206a353ca38d4fdf6e)
https://github.com/PX4/NuttX-apps/compare/91b6ad6a0d00ac107088b18588cd54d40e3cb796...de4d52d465fee9cb9ed48e8d1b8d73e8f5888519

de4d52d4 (HEAD -> master, origin/master) wireless: gs2200m: Add support for setsockopt_request()
c5673957 Remove unused BUILTIN_PROXY_STACKSIZE config
44b8c9c5 apps/examples/tcpblaster:  Fix compile errors in loopback mode.
539d0854 examples: elf: Fix warnings when compiled for RISC-V 64bit
779197c6 Ensure all source code end with one and only one newline
4a13a089 testing/smp: Replace up_cpu_index with sched_getcpu
d2e1c8a4 apps/wireless/gs2200m/gs2200m_main.c:  Eliminate a warning
c8dbd59e netutils/telnetd/telnetd_daemon.c: Avoid a warning if CONFIG_NET_SOCKOPTS=n
d2522e28 apps/netutils/telnetd:  Fix undefined reference to setsockopt.
f14aead5 Shouldn't use local readline in telnet